version: '2'
services:
  gms4u-mysql:
    image: mysql:8.0.20
    # volumes:
    #     - ~/volumes/jhipster/gms4u/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=teknikality
      - MYSQL_PASSWORD=Teknikality786
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=gms4u
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
