export const enum BookingStatus {
  IN_PROGRESS = 'IN_PROGRESS',

  COMPLETED = 'COMPLETED',

  CONFIRMED = 'CONFIRMED',

  PENDING = 'PENDING',

  CANCELLED = 'CANCELLED',

  INVOICED = 'INVOICED',
}
